In [189]:
import pandas as pd
import numpy as np

In [160]:
use_columns = ['code',
               'countries_en',
               'additives_n',
               'nutriscore_score',
               'nutriscore_grade',
               'nova_group',
               'pnns_groups_2',
               'fat_100g',
               'carbohydrates_100g',
               'sugars_100g',
               'fiber_100g',
               'proteins_100g',
               'salt_100g']

In [162]:
data = pd.read_csv('en.openfoodfacts.org.products.csv',
                   sep='\t',
                   low_memory=False,
                   usecols=use_columns,
                   index_col='code')

In [164]:
data

,countries_en,additives_n,nutriscore_score,nutriscore_grade,nova_group,pnns_groups_2,fat_100g,carbohydrates_100g,sugars_100g,fiber_100g,proteins_100g,salt_100g
code,,,,,,,,,,,,
0000000000017,France,NaN,NaN,NaN,NaN,unknown,7.0,70.1,15.0,NaN,7.8,1.40
0000000000031,France,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN
000000000003327986,Spain,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN
0000000000100,France,0.0,18.0,d,NaN,Dressings and sauces,8.2,29.0,22.0,0.0,5.1,4.60
00000000001111111111,France,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
9999999900686,Belgium,NaN,NaN,NaN,NaN,Sweets,NaN,NaN,NaN,NaN,NaN,NaN
9999999901,United Kingdom,NaN,NaN,NaN,NaN,unknown,12.0,2.0,1.0,NaN,1.0,1.00
9999999910128,Réunion,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN
9999999990397,Belgium,NaN,NaN,NaN,NaN,unknown,0.3,2.4,0.6,NaN,1.6,0.64
999999999999999,France,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN

In [165]:
clean_data = data[data['nutriscore_score'].notnull() & data['countries_en'].notnull()]

In [167]:
country_lists = clean_data['countries_en'].str.split(',')
country_counts = country_lists.explode().value_counts()
top_countries = country_counts[country_counts > 1000]

In [168]:
top_countries

France            237587
United States     237284
Spain              47170
Germany            27194
Switzerland        13833
Belgium            12273
United Kingdom      6398
Italy               5449
Mexico              3872
Poland              2644
Netherlands         2302
Canada              2226
Sweden              2036
Australia           2019
Austria             1938
Portugal            1330
Thailand            1274
Romania             1032
Finland             1002
Name: countries_en, dtype: int64

In [169]:
use_countries = top_countries[top_countries > 1000].index.tolist()
clean_data = clean_data[clean_data['countries_en'].isin(use_countries)]

In [171]:
clean_data

,countries_en,additives_n,nutriscore_score,nutriscore_grade,nova_group,pnns_groups_2,fat_100g,carbohydrates_100g,sugars_100g,fiber_100g,proteins_100g,salt_100g
code,,,,,,,,,,,,
0000000000100,France,0.0,18.0,d,NaN,Dressings and sauces,8.2,29.0,22.0,0.0,5.1,4.60
0000000000949,France,NaN,1.0,b,NaN,One-dish meals,0.3,5.3,3.9,NaN,0.9,0.42
0000000001281,France,NaN,14.0,d,NaN,Biscuits and cakes,22.0,27.3,21.9,4.4,4.6,0.10
0000000001885,France,NaN,-2.0,a,NaN,Fruits,0.0,36.0,27.0,3.6,0.6,0.00
0000000002257,France,NaN,1.0,b,NaN,One-dish meals,12.7,3.9,1.0,NaN,1.9,0.27
...,...,...,...,...,...,...,...,...,...,...,...,...
9999991042742,France,NaN,17.0,d,NaN,unknown,27.0,19.0,18.0,NaN,6.0,0.19
9999991149090,France,NaN,0.0,b,NaN,Cereals,0.5,80.0,0.0,NaN,7.0,0.00
9999999004360,France,NaN,15.0,d,NaN,unknown,20.2,30.9,10.4,NaN,7.4,1.10
9999999175305,Germany,3.0,12.0,d,4.0,Biscuits and cakes,7.6,35.0,24.0,NaN,2.6,0.28
99999995,France,NaN,-2.0,a,NaN,Meat,5.0,0.0,0.0,NaN,21.5,0.18

In [192]:
clean_data = clean_data.replace(to_replace=['unknown',''], value=np.nan)

In [194]:
clean_data.to_csv('clean_data.csv', sep=';', na_rep='NA')